### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by alexattia** [HealthplusAI/python3-gdcm#1]
Hello,  
Thank you for your indications.
However, while following them, I am facing an issue 
```
>>> import gdcm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/venv/lib/python3.5/site-packages/gdcm.py", line 62, in <module>
    from gdcmswig import *
  File "/home/alex/venv/lib/python3.5/site-packages/gdcmswig.py", line 30, in <module>
    _gdcmswig = swig_import_helper()
  File "/home/alex/venv/lib/python3.5/site-packages/gdcmswig.py", line 26, in swig_import_helper
    _mod = imp.load_module('_gdcmswig', fp, pathname, description)
  File "/home/alex/venv/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/alex/venv/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__gdcmswig)
```

My configuration is :  
Ubuntu 16.04
Working in a virtual environment
Python 3.5 

Thank you very much for any help

**Comment by alexattia** [comment]
and while trying with a virtual env with Python 3.6, I have this error 
```
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by Luxas98** [comment]
Thank you for info, I added note that the prebuild wrapper was build for python3.6 and Ubuntu18.04, for other OS I assume follow local rebuild instructions.

Also added `libpython3.6-dev` for installation just in case in README.md

I do not plan to do not plan to do pre python3.6 integration for now, neither Ubuntu18.04 but if somebody has time its more welcome to drop me message for more info.
